<?php
	function sendMail($name,$emailid,$message)
	{
		//send mail
			$sender = $emailid;
			$receiver = "mail@jeclat.in";
			$client_ip = $_SERVER['REMOTE_ADDR'];
			$email_body = "Name: " . stripslashes($name) . "\nEmail: " . stripslashes($sender) . " \n\nSubject: Feedback Form \n\nMessage: \n\n" . stripslashes($message) . " \n\nIP: " . $client_ip . "\n\nAutomated email generated by www.jeclat.in.";		
			$extra = "From: " . stripslashes($sender) . "\r\n" . "Reply-To: " . stripslashes($sender) . "\r\n" . "X-Mailer: PHP/" . phpversion();
			
			$email_body_auto_reply = "Hello " . stripslashes($name) . ", \n\nThis is an auto reply message. Thank you for your feedback. \n\nFrom, \nAdmin \nwww.jeclat.in";
			$extra_auto_reply = "From: mail@jeclat.in\r\nReply-To: " . stripslashes($receiver) . "\r\n" . "X-Mailer: PHP/" . phpversion();
			
			mail( $sender, "JECLAT 2013 Feedback :: Auto-reply", $email_body_auto_reply, $extra_auto_reply );
		
			mail( $receiver, "JECLAT 2013 :: Feedback", $email_body, $extra );
	}
?>
<?php 
	require_once('module-config.php');
 	require_once('module-sql-connect.php');
	$dateofentry=date(__DATE_FORMAT_IP__);
	$name=addslashes(strip_tags(trim($_POST['na'])));
	$emailid=addslashes(strip_tags(trim($_POST['em'])));
	$message=addslashes(strip_tags(trim($_POST['ms']))); 
	$flag_incomplete=0;
	$flag_sqlfail=0;
	$flag_emailid=0;
	if($name=='' || $message=='')
	{
		$flag_incomplete=1;
		$err_occured=1;
	}
	if ($emailid!="" && !filter_var($emailid, FILTER_VALIDATE_EMAIL))
	{
		$flag_emailid=1;
		$err_occured=1;
	}
	if($err_occured!=1)
	{
		$tbl_name=__SQL_TABLE_PREFIX__ . "feedback";
		$sql_query="INSERT INTO $tbl_name(name,emailid,timestamp,message) VALUES('$name','$emailid','$dateofentry','$message')";
		$query_result=mysql_query($sql_query);
		if(!$query_result)
		{
			$flag_sqlfail=1;
			$err_occured=1;
		}
		else
		{
			@sendMail($name,$emailid,$message);			
		}
	}
	mysql_close($con);
	$err_string="";
	if($err_occured==1)
	{
		if($flag_sqlfail==1 || $flag_confail==1)
		{
			$err_string='Feedback submission failed due to a technical problem. Sorry for the inconvenience. Please try again later!';
		}
		else if($flag_incomplete==1)
		{
			$err_string=$err_string . 'One or more fields empty!';
		}
		else if($flag_emailid==1)
		{
			$err_string=$err_string . 'The email address you provided is invalid. Please provide a correct email address!';
		}
	}
	else
	{
		$err_string='POST_SUCCESS';
	}
	echo $err_string;
?>
